name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo lint step is running ... 
  
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - run: echo build step is running ... 
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo test step is running ... 
  
  publish:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    steps:
      - run: echo publish step is running ... 
